# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/NanoProc/project_3/project_3.cache/wt [current_project]
set_property parent.project_path H:/NanoProc/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/NanoProc/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/4_Bit_Add_Sub_Unit.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/Adder_3B.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/sources_1/imports/new/D_FF.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/FA.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/HA.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/Instruction_Decoder.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/LUT_16_7.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/LUT_8_3.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/LowerPartTest.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/MUX_2_3.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/MUX_2_4.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/MUX_8_4.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/sources_1/new/Programme_Counter.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/RCA_4.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/ROM_3_T0_12.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/sources_1/imports/new/Reg.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/sources_1/new/Reg_Bank.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/sources_1/imports/new/Slow_Clk.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/imports/new/UpperPartTest.vhd
  H:/NanoProc/project_3/project_3.srcs/sources_1/new/Processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Sadeesha/Desktop/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/Sadeesha/Desktop/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
